CREATE TABLE public.todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  task TEXT CHECK (char_length(task) > 3),
  is_complete BOOLEAN DEFAULT FALSE,
  inserted_at TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL
);